### ISSUE TITLE
PHP fatal error in context file leads to node process stucking

### ISSUE THREAD

**Issue by jazzfog** [Behat/en-mink.behat.org#26]
I have such case: PHP fatal error in context (like attempt to click not existing button `$this->getSession()->getPage()->findButton('NotExisting')->click();`) leads to `Node` process stucking - repeated `Behat` start fails because `Node` can not reuse port which is already in use.

First start
```
# php ./composer/vendor/behat/behat/bin/behat

...[feature description skipped]...

PHP Fatal error:  Call to a member function click() on a non-object 
in /project/tests/behat/features/bootstrap/Search.php on line 17

Fatal error: Call to a member function click() on a non-object 
in /project/tests/behat/features/bootstrap/Search.php on line 17
```

Second start and further
```
# php ../../composer/vendor/behat/behat/bin/behat

...[feature description skipped]...

Server process has been terminated: (8) [
events.js:72
	  throw er; // Unhandled 'error' event
			^
Error: listen EADDRINUSE
  at errnoException (net.js:904:11)
  at Server._listen2 (net.js:1042:14)
  at listen (net.js:1064:10)
  at net.js:1146:9
  at Object._onImmediate (/usr/lib/node_modules/zombie/lib/zombie/dns_mask.js:69:16)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
] (RuntimeException)
```

So all my further calls will fail, and the only thing i can do here is to go to server, run `netstat -tulpn` and `kill <node PID>`.

Is there anything you can do about it?

**Comment by stof** [comment]
This repo is about the Mink documentation (the outdated Mink doc to be exact). Please report your issue on MinkZombieDriver instead.
